#!/bin/bash
echo -e "Update Raspbian? (y/n): \c"
read answer
if [[ "$answer" = 'y' ]] || [[ "$answer" = 'Y' ]];
then
  # Update raspbian
  echo "deb http://archive.raspbian.org/raspbian/ stretch main" >> /etc/apt/sources.list
  apt-get update
  apt-get upgrade
else
  :
fi


echo -e "Install dependencies? (y/n): \c"
read answer
if [[ "$answer" = 'y' ]] || [[ "$answer" = 'Y' ]];
then
  # Install packages
  apt-get -y install python-pip python-pygame python-serial apache2 mysql-server-5.6 php5 php5-mysql phpmyadmin python-mysqldb
  pip install pynmea2
else
  :
fi

# Make script start at boot
rm /etc/rc.local
cp /home/pi/VeraHMI/Init/rc.local /etc/rc.local
chmod 777 /etc/rc.local

# Map usb devices to persistent names 
rm /etc/udev/rules.d/99-usb-serial.rules
cp /home/pi/VeraHMI/Init/99-usb-serial.rules /etc/udev/rules.d/99-usb-serial.rules
chmod 777 /etc/udev/rules.d/99-usb-serial.rules


echo -e "Set up mysql? (y/n): \c"
read answer
if [[ "$answer" = 'y' ]] || [[ "$answer" = 'Y' ]];
then
  # MySQL Setup
  user="root"
  password="verateam" 
  database="Vera"
  mysql --user="$user" --password="$password" --execute="CREATE DATABASE $database;"
  mysql --user="$user" --password="$password" --database="$database" --execute="CREATE TABLE HMILog (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, day DATE NOT NULL, timestamp TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), level INT(11) NOT NULL, module VARCHAR(20) NOT NULL, msg VARCHAR(50) NOT NULL, lat_loc VARCHAR(20) NOT NULL, long_loc VARCHAR(20) NOT NULL);"
  mysql --user="$user" --password="$password" --database="$database" --execute="CREATE TABLE ECULogs (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, timestamp TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3));"
else
  :
fi


echo -e "Copy config strings to /boot/config.txt and add phpmyadmin support for apache server? (y/n): \c"
read answer
if [[ "$answer" = 'y' ]] || [[ "$answer" = 'Y' ]];
then
  # Set up screen and disable boot to GUI
  echo "framebuffer_width=640" >> /boot/config.txt
  echo "framebuffer_height=480" >> /boot/config.txt
  echo "disable_splash=1" >> /boot/config.txt
  echo "max_usb_current=1" >> /boot/config.txt
  echo "disable_overscan=1" >> /boot/config.txt
  echo "enable_uart=1" >> /boot/config.txt
  


  # Set up phpmyadmin
  echo "Include /etc/phpmyadmin/apache.conf" >> /etc/apache2/apache2.conf
  /etc/init.d/apache2 restart
else
  :
fi


# Set up as access point
echo -e "Set up RPi network settings (WiFi, 4G and ethernet)? (y/n): \c"
read answer
if [[ "$answer" = 'y' ]] || [[ "$answer" = 'Y' ]];
then
  sudo apt-get -y install hostapd isc-dhcp-server

  cp /home/pi/VeraHMI/Init/dhcpd.conf /etc/dhcp
  chmod 755 /etc/dhcp/dhcpd.conf

  cp /home/pi/VeraHMI/Init/isc-dhcp-server /etc/default
  chmod 755 /etc/default/isc-dhcp-server

  cp /home/pi/VeraHMI/Init/interfaces /etc/network/interfaces
  chmod 755 /etc/network/interfaces

  cp /home/pi/VeraHMI/Init/hostapd.conf /etc/hostapd
  chmod 755 /etc/hostapd/hostapd.conf

  cp /home/pi/VeraHMI/Init/hostapd /etc/default
  chmod 755 /etc/default/hostapd

  wget http://www.adafruit.com/downloads/adafruit_hostapd.zip 
  unzip adafruit_hostapd.zip 
  mv /usr/sbin/hostapd /usr/sbin/hostapd.ORIG 
  mv hostapd /usr/sbin
  chmod 755 /usr/sbin/hostapd
else
  :
fi


reboot




