#!/usr/bin/env python

from GUI.GUI import GUI
from src.ECUHandler import ECUHandler
from src.MySQLConnection import MySQLConnection

import sys, os.path

import threading

try:
	mysql = MySQLConnection()
	gui = GUI(mysql)
	gui.attributes("-fullscreen", True)
	# Only runs buttonHandler if the software is running on raspbian ("linux2")
	if sys.platform == "linux2":
		from src.PhysicalButtonHandler import PhysicalButtonHandler
		#Start to listen for button presses
		#PhysicalButtonHandler = PhysicalButtonHandler(gui)
		#PhysicalButtonHandler.start()

		from src.GPSHandler import GPSHandler
		GPSHandler = GPSHandler(gui)
		GPSHandler.start()

		ECUHandler = ECUHandler(gui, GPSHandler, mysql)
		ECUHandler.start()
	else:
		ECUHandler = ECUHandler(gui, None, mysql)
		ECUHandler.start()
		print("""
				You're not running this program on Raspberry Pi, 
				button presses will be ignored and GPS will be disabled, 
				continuing...""")

	gui.mainloop()
	
except (KeyboardInterrupt, SystemExit):
	print("Exiting...")
	sys.exit()
