#!/usr/bin/env python

from src.ECUHandler import ECUHandler
from src.MySQLConnection import MySQLConnection
from GUI.GUI import GUI

import sys, os.path, threading



	


try:
	global gui
	mysql = MySQLConnection()
	gui = GUI(mysql)

	gui.attributes("-fullscreen", True)
	# Only runs buttonHandler if the software is running on raspbian ("linux2")
	if sys.platform == "linux2":

		#initalize GPS
		from src.GPSHandler import GPSHandler
		GPSHandler = GPSHandler(gui)
		GPSHandler.start()

		#Initialize ECUHandler
		ECUHandler = ECUHandler(gui, GPSHandler, mysql)
		ECUHandler.start()

		# Handle button presses 
		from src.ButtonHandler import ButtonHandler
		buttonHandler = ButtonHandler(gui)
		buttonHandler.start()
	else:
		ECUHandler = ECUHandler(gui, None, mysql)
		ECUHandler.start()
		print("You're not running this program on Raspberry Pi, button presses will be ignored and GPS will be disabled, continuing...")

	gui.mainloop()
	
except (KeyboardInterrupt, SystemExit):
	print("Exiting...")
	sys.exit()
